### ISSUE TITLE
The JavaMelody Monitoring chart shows garbled characters

### ISSUE THREAD

**Issue by Linktech-Jason** [javamelody/jira-confluence-javamelody#11]
After upgrade Jira to 8.13.1 ,the JavaMelody Monitoring chart shows garbled characters.

![image_2020_12_01T05_48_27_008Z](https://user-images.githubusercontent.com/75597818/101306970-438a3600-3881-11eb-9997-f4496c1b20c9.png)
Confirmed that the system encoding is UTF-8, but there are still errors displayed on the chart

**Comment by evernat** [comment]
I suppose that what I see is Chinese characters. And the issue is probably with the fonts in the server OS for the charts, for Chinese characters.

So I suggest to check the fonts in the OS:
`fc-list`

And you can try to install the following fonts, for example when using yum:
`yum install dejavu-sans-fonts.noarch dejavu-sans-mono-fonts.noarch`

Another user said that `yum groupinstall chinese-support` was successful, instead of the above.
