### ISSUE TITLE
Compatibility with Jira Data Center 8.5

### ISSUE THREAD

**Issue by dgodoyAtsistemas** [javamelody/jira-confluence-javamelody#13]
Hi team,

We are going to migrate Jira server license to data center license, but this app isn't supported on data center according to hosting options in the Atlassian marketplace. Really, is this app supported on data center or not?

Thank you.

Regards,
Diego.

**Comment by evernat** [comment]
The javamelody monitoring plugin is compatible with data center since the beginning.
It is officially approved by Atlassian as data center compatible since February 2019, but it could not be published as such because of an issue in the Atlassian marketplace (AMKT-22246), until beginning of July, 2021.
Since then, the plugin is pending review by Atlassian to be published (Yana Maletska changed the status to AR UNDER REVIEW on the July 9).

**Comment by evernat** [comment]
for reference; https://github.com/javamelody/javamelody/wiki/AtlassianPlugin#atlassian-data-center

**Comment by dgodoyAtsistemas** [comment]
Thanks for the info @evernat.
