### ISSUE TITLE
Vulnerability reported in Confluence for Java Melody plugin

### ISSUE THREAD

**Issue by Rajat-Github100** [javamelody/jira-confluence-javamelody#26]
Hi Team

We received a report from our security team that there is malware detected under the javamelody folder.
Could you please check and let us know more about this. (attached snapshot).
Let me know if you require any further information.
<img width="376" alt="vulnerability" src="https://user-images.githubusercontent.com/121790122/210219079-57002874-4d30-4730-bb9f-3d545e8dbc95.png">

**Comment by evernat** [comment]
rrd files are "round robin database" made by javamelody with the jrobin library to store metrics values. They are used to display graphs in the monitoring page. I am absolutely sure that rrd files are not malware. This is a false positive.

In case that your anti-malware detects a malware perhaps just because the file name is httpSessions, then it is a poor detection.
