### ISSUE TITLE
Unable to upgrade javamelody on confluence version 7.4.17

### ISSUE THREAD

**Issue by Soumyakanta-7** [javamelody/jira-confluence-javamelody#30]
Unable to upgrade javamelody on confluence version 7.4.17

**Comment by Soumyakanta-7** [comment]
Hi Team,

Currently we are upgrading user installed apps on confluence version 7.4.17. Since the javamelody app is outdated atlassian support team suggested to replace the jira-confluence-javamelody.jar file with new one, But i could not find any file with this name on our servers.
Kindly help us to upgrade the app.

Regardst,
Soumyakanta

**Comment by evernat** [comment]
See doc at https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

You can download the latest version at https://github.com/javamelody/jira-confluence-javamelody/releases (currently 1.95.0)

As said in the doc, for Confluence, the plugin is in general installed or uninstalled using the Plugin manager in the Administration menu of Confluence.
Otherwise the jar file is named using a pattern like jira-confluence-javamelody-x.y.z.jar as you can see in the releases above, that is not exactly jira-confluence-javamelody.jar file.
