### ISSUE TITLE
Cloudwatch Dependency Missing

### ISSUE THREAD

**Issue by Mystik738** [javamelody/jira-confluence-javamelody#4]
In the main javamelody repo there's the ability to push statistics to cloudwatch (https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-aws-cloudwatch) however to do that with this repository, end users have to download the code and build with the following dependency added to the pom file:

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-cloudwatch</artifactId>
    <version>1.11.136</version>
</dependency>
```

**Comment by evernat** [comment]
I recommend that you don't do that and that you put back the original jar file for JIRA/Confluence/Bamboo/Bitbucket, because otherwise you may have versions conflicts between transitive dependencies like httpcore and joda-time and more recent versions of the same jar files in WEB-INF/lib of JIRA/Confluence/Bamboo/Bitbucket.

Otherwise, this may cause regressions in some features of JIRA/Confluence/Bamboo/Bitbucket.

In fact, the doc for AWS Cloudwatch was not explicit in case of JIRA/Confluence/Bamboo/Bitbucket.
I have completed that doc at:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-aws-cloudwatch

Here is an extract:
> If JIRA/Confluence/Bamboo/Bitbucket/Liferay/Sonar/Alfresco, download this [aws-cloudwatch-library.hpi](https://github.com/javamelody/aws-cloudwatch-library/releases/download/1.11.136/aws-cloudwatch-library.hpi) file then open it using a zip manager and copy the WEB-INF/lib/*.jar files to the webapp's WEB-INF/lib directory, excluding jar files which already present in the webapp (for example, the atlassian-jira/WEB-INF/lib directory already contains more recent versions of httpcore and of joda-time jar files).

You can do as documented now after putting back the original version of the javamelody jar file for JIRA/Confluence/Bamboo/Bitbucket.
