### ISSUE TITLE
Delisted from marketplace?

### ISSUE THREAD

**Issue by mdavoodi** [javamelody/jira-confluence-javamelody#5]
The Atlassian Marketplace listing disappeared. I can only see the version page now. What happened?

**Comment by evernat** [comment]
Yes I know, sorry. But you can find it at:
https://plugins.atlassian.com/plugins/net.bull.javamelody

I thought that the "hidden" warning was caused by an issue in the marketplace to publish the data center compatibility (the plugin is accepted as compatible with data center by Atlassian, but it cannot be published as such at the moment).
But it was not the cause.
In fact, I have forgotten to add a link to the privacy policy and EULA, for GDPR. It's done since yesterday and I expect Atlassian to unhide the plugin soon. (But still not displayed as data center compatible in the marketplace.)

**Comment by evernat** [comment]
The plugin is now listed again in the marketplace.
